### ISSUE TITLE
[Request] Add documentation with simple HTTP endpoints

### ISSUE THREAD

**Issue by CombainerA19** [Stability-AI/api-interfaces#56]
Sometimes over advancment create problems. 

Greetings. I am looking to implement my workflows with simple HTTP requests GET/POST, they usually include:

- basic URL for request
- method / endpoint (i.e. text-to-image / image-to-image...)
- headers (i.e. API key)
- parameters (i.e. size of img, version of SD, CFG scale, steps)

Example of minimum data that can be send to API as JSON:

stability.ai/api/txt2img
{
"prompt":"invisible crocodile",
"cfg scale": "11",
"steps": "150",
"number of img": "3",
}
_and all other settings will be default of some kind, however could be also customized via request_

**Requesting Stability AI team and community to share documentation regarding simple HTTP API for people who are not console coders. Thank you!** 

P.s. reference to simple API by Twitter: https://developer.twitter.com/en/docs/twitter-api/migrate/twitter-api-endpoint-map

**Comment by feizhaojun** [comment]
Stability use gRPC implementation, I'm afraid there is no public HTTP API available by the team.

**Comment by johnsabath** [comment]
Exciting news, we have a REST API in developer preview!  https://api.stability.ai/docs

**Comment by drewlustro** [comment]
> Exciting news, we have a REST API in developer preview! [api.stability.ai/docs](https://api.stability.ai/docs)

Wow, that works great. Thank you!
