### ISSUE TITLE
Add image strength option in Image to Image prompts

### ISSUE THREAD

**Issue by Moe03** [Stability-AI/api-interfaces#63]
I can't seem to find the image strength option which is available is dreamstudio but not in the API, is this option already available or not yet?

**Comment by pharmapsychotic** [comment]
You want to fill in the `schedule` field of StepParameters and adjust the `start` value. For example `start` at 0.25 for having an init image strength of 75% (or can think of it has 25% denoising strength)

It's pretty nested in there but look under Request.image.parameters[].schedule.start
