### ISSUE TITLE
Where is the tensors.proto

### ISSUE THREAD

**Issue by denghuichao** [Stability-AI/api-interfaces#82]
<img width="515" alt="wecom-temp-9aaf4f4cfb60263465639472c49032a9" src="https://github.com/Stability-AI/api-interfaces/assets/8939389/8b741c3f-c8f5-4c3e-b193-09dec7076cc9">

**Comment by huo-ju** [comment]
It's a tensor serialization lib, which in the src dir as a submodule  https://github.com/Stability-AI/api-interfaces/tree/main/src

More specifically:
https://github.com/coreweave/tensorizer/blob/35381e3812ba342991d30b71ce257503622ae828/proto/tensors.proto
